verb=input("name a verb")
noun=input("give me a noun")
adjective=input("give me an adjective")
verb2=input("give me 2nd verb")
noun2=input("give me 2nd noun")
verb3=input("give me a 3rd verb")
place=input("give me a place not on earth")
adjective2("give me a 2nd adjective")
print("I",verb,"to mars the we climbed on a",noun)
